name: Notebook Formatting
on: [push, pull_request]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black nbstripout nbconvert
      - name: Convert notebooks to scripts
        run: |
          find . -name "*.ipynb" -exec jupyter nbconvert --to script {} \;
      - name: Run Black on scripts
        run: |
          find . -name "*.py" -exec black {} \;
      - name: Convert scripts back to notebooks
        run: |
          find . -name "*.py" -exec jupyter nbconvert --to notebook --execute --inplace {} \;
      - name: Set Git Identity
        run: |
          git config --global user.email "flam0799@gmail.com"
          git config --global user.name "Elias Xu"
      - name: Check for changes
        run: |
          git diff --quiet || git commit -am "Automated formatting changes"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          commit-message: "Automated formatting changes"
          title: "Automated formatting changes"
          body: "This is an auto-generated PR with formatting changes."
          branch: "formatting-changes"
          base: 'main'  # replace 'main' with your default branch if it's different
